# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'MyProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyProject

pod 'JSONModel’, '~> 1.0.2'
pod 'Masonry', '~> 0.6.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'AFNetworking', '~> 3.1.0'

  target 'MyProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
